name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build warehouse
      uses: actions/checkout@v2
    - run: docker build ./Warehouse.Api --tag exedary/warehouse
    - name: Build warranty
      uses: actions/checkout@v2
    - run: docker build ./Warranty.Api --tag exedary/warranty
    - name: Publish
      env: 
        HEROKU_KEY: ${{secrets.HEROKU_KEY}} 
      run: |
        docker login --username=exedary@gmail.com --password=$HEROKU_KEY registry.heroku.com
        docker push exedary/warehouse:latest
        docker push exedary/warranty:latest
        
