name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build warehouse
      uses: actions/checkout@v2
    - run: docker build ./Warehouse.Api --tag registry.heroku.com/microserviceswarehousedb/web
    - name: Build warranty
      uses: actions/checkout@v2
    - run: docker build ./Warranty.Api --tag registry.heroku.com/warehousemicroservice/web
    - name: Publish
      env: 
        HEROKU_KEY: ${{secrets.HEROKU_KEY}} 
      run: |
        docker login --username=exedary@gmail.com --password=$HEROKU_KEY registry.heroku.com
        docker push registry.heroku.com/warehousemicroservice/web
        docker push registry.heroku.com/microserviceswarehousedb/web
        
  deployWarehouse:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "warehousemicroservice" #Must be unique in Heroku
          heroku_email: "exedary@gmail.com"
          usedocker: true
          appdir: "Warehouse.Api"     
        env:
          WAREHOUSE_DB: ${{secrets.WAREHOUSE_DB}}
      - run: docker run -d -p 80:8081 -e WAREHOUSE_DB=$WAREHOUSE_DB registry.heroku.com/warehousemicroservice/web
            
  deployWarranty:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "microserviceswarehousedb" #Must be unique in Heroku
          heroku_email: "exedary@gmail.com"
          usedocker: true
          appdir: "Warranty.Api"
        env:
          WARRANTY_DB: ${{secrets.WARRANTY_DB}}
      - run: docker run -d -p 80:8080 -e WARRANTY_DB=$WARRANTY_DB registry.heroku.com/microserviceswarehousedb/web         
