name: Deploy

on:
  push:
    branches:
      - master

jobs:
  buildWarehouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "microserviceswarehousedb" #Must be unique in Heroku
          heroku_email: "exedary@gmail.com"
          usedocker: true
      - name: deployWarehouse
        with: 
          appdir: "Warehouse.Api"        
        env:
          HD_WAREHOUSE_DB: ${{secrets.WAREHOUSE_DB}}
        run: |
            docker run -d -p 8081:8081 exedary/warehouse:latest
      - name: deployWarranty
        with:
          appdir: "Warranty.Api"
        env:
          HD_WARRANTY_DB: ${{secrets.WARRANTY_DB}}
        run: |
            docker run -d -p 5053:5053 exedary/warranty:latest
        
      